### ISSUE TITLE
¿Cómo anexo las tablas en mi manuscrito?

### ISSUE THREAD

**Issue by dahianagb07** [biogeografia-201902/datos-hormigas-campus-uasd#1]
Hola @geofis, ya comenzamos con las preguntas profundas del manuscrito. Quiero saber como anexar en mi manuscrito las tablas que están en Datos Hormigas UASD, recuerde que usted nos enseño hacerlo en la carpeta Vertedero pero no como ponerla en el manuscrito.

**Comment by geofis** [comment]
@dahianagb07 Creo que lo respondí en el aula. Cierro el *issue*.
